### ISSUE TITLE
Add QuillCTF to the Repository

### ISSUE THREAD

**Issue by Sm4rty-1** [blockthreat/blocksec-ctfs#39]
Hi, This is an amazing archive of Capture the Flag (CTF) competitions. Recently, we released a CTF based on Smart contract Security i.e. QuillCTF, which we believe could be a great addition to your repository. We also received a good response from the web3 security community regarding the CTF.

Here is the link: https://bit.ly/QuillCTF

It would be great if you include QuillCTF in your repository.
Thanks,

**Comment by iphelix** [comment]
Thanks friend! Could you add a PR to the README with info for the CTF?

**Comment by Sm4rty-1** [comment]
Yes Sure!!
